### PR TITLE
Added hook UseAnimateObject.

### PR DESCRIPTION
**Pull request by FakelsHub**
Added a new script hook (issue #119) allowing to replace or skip the animation when using map objects.
Is the name correct for the hook or does it need to be changed?

### CODE REVIEW

**Comment by NovaRain** [comment]
I would name it HOOK_USESCENERYOBJ.

**Comment by FakelsHub** [comment]
Containers object does not belong to the scenery
so can UseMapObject ? :)

**Comment by FakelsHub** [comment]
can name useanimationobj ?, because it is not quite the use of the object.

**Comment by NovaRain** [comment]
>can name useanimationobj ?, because it is not quite the use of the object.
How about HOOK_USEANIMOBJ?

**Pull request merged**
