### PR TITLE
Additional game msg file reading (#2)

### PR DESCRIPTION
**Pull request by Vennor**
This is the second approach on adding the possibility to read more game msg files than the hardcoded ones.

Previous pull request is #41.

Among other changes - like fixing a potential memory leak in **ReadExtraGameMsgFiles** - this time file reading is done from the **MainMenu** function which is called after main menu initialization.

There's one special place in the **MainMenu** function. At first I added a **ReadExtraGameMsgFiles** call before the **__asm** block, but that triggered an assertion when dereferencing iterators of the **gExtraGameMsgLists** map. Turns out the call has to be made between the **pushad** and **popad** ops, otherwise it corrupts the map somehow if the **MainMenu** function is called more than once. This happened only in the debug mode.

NovaRain's suggestions and findings from the previous pull request regarding the tr1 and headers are included.

### CODE REVIEW

**Comment by NovaRain** [comment]
I still got the premature termination issue on scripts if message_str_game can't get a valid msg file or line.

**Comment by Vennor** [comment]
Got it. Looks like this is what happens without my changes to op_message_str_game2.

1. **const char* msg** is left uninitialized.
2. None of the conditions is met in the if-else-if block.
3. **if (msg != 0)** is met, so **SetOpReturn(msg);** is called.
4. The function returns an uninitialized pointer as the message string.

This is bad, but just happens to work most of the time. On the other hand after my changes this is what happens.

1. **const char* msg** is left uninitialized.
2. The last condition, **else if (fileId >= 0x2000)**, is met in the if-else-if-else-if block.
3. When you request a nonexistent message line **msg = GetMsg(it->second, msgId, 2);** causes 0 to be assigned to **msg**. Or when you request a line from a nonexistent file **msg  = 0;** causes the same.
4. **if (msg != 0)** is not met, so **SetOpReturn(0, DATATYPE_INT);** is called.

This causes an integer type to be returned to the script engine and **display_msg** will interrupt when it is not given a string value as a parameter.

I basically fixed a bug which caused a design flaw to manifest itself.

Available solutions are.

1. Use implicit conversion to string through addition, eg. **display_msg("" + message_str_game(0x2000, 100));**. This is bad, since it would require doing this all the time.
2. Replace the **if (msg != 0)** check with error message assignment, eg. **if (msg == 0) msg = "Error";** and always use **SetOpReturn(msg);**. That's the way to go!

**Comment by Vennor** [comment]
The fix is now commited.

**Comment by NovaRain** [comment]
The fix works in my testings. No more premature termination or garbage characters, only good ol' "Error" in the message box. :)
Currently I merge your code into "develop" branch. It would be nice if you could base your changes on the latest "develop" branch next time, as it would make merging easier (at least for an amateur like me.) Usually phobos2077 and I don't commit changes to master directly.

**Comment by Vennor** [comment]
Great news! I'll be sure to use the develop branch next time. Thanks for the hint.

**Pull request merged**
