### PR TITLE
Fixed function "get_attack_type" and new function "attack_is_aimed".

### PR DESCRIPTION
**Pull request by FakelsHub**
`attack_is_aimed` - Returns true(1), if the aimed attack mode is selected, otherwise 0.

Fix broken function for v3.8
```
static void __declspec(naked) get_attack_type() {
	__asm {
		push edx;
		push ecx;
		push eax;
		sub esp, 8;
		lea edx, [esp];
		lea eax, [esp+4];
		call intface_get_attack_;
		add esp, 4;	// is_secondary
		test eax, eax;
		jz jskip;
		add esp, 4;
                // get reload
		cmp ds:[_interfaceWindow], eax;
		jz jend;
		mov ecx, ds:[_itemCurrentItem];  // 0 - left, 1 - right
		imul edx, ecx, 0x18;
		cmp ds:[_itemButtonItems+5+edx], 1; // .itsWeapon
		jnz jend;
		lea eax, [ecx+6];
		jmp jend;
jskip:
		pop eax;	// hit_mode
jend:
		pop ecx;
		_RET_VAL_INT(ecx);
		pop ecx;
		pop edx;
		retn;
	}
}
```
`const DWORD intface_get_attack_ = 0x45EF6C;` - for FalloutEngine.cpp

### CODE REVIEW

**Comment by NovaRain** [comment]
get_attack_type still doesn't return correct values for "reload" in both hands (now -1).

**Comment by FakelsHub** [comment]
fixed reloading (implementation is taken from crafty), in 3.8 works, need check in v4.0

**Comment by NovaRain** [comment]
attack_is_aimed returns 0 for non-aimed attacks and -1 for all other non-attack modes, not just function error. Kinda redundant IMO.

**Comment by FakelsHub** [comment]
Исправил условие возврата.

**Pull request merged**
