### PR TITLE
Hook set explosion timer.

### PR DESCRIPTION
**Pull request by FakelsHub**
Runs after setting the timer for explosives, allows you to overrides the engine parameters to set the timer.

int     arg1 - the time in ticks at which the timer was set
obj     arg2 - explosive item
int     arg3 - engine calculate: 1 - failure, 2- success

int     ret1 - set new explosion time (maximum 18000 ticks)
int     ret2 - pass the value determine whether the timer was set successfully: 1 - failure, 2 - success (values are similar ROLL_* see Define.h) otherwise the calculation of the engine's handler will be used.

### CODE REVIEW

**Comment by FakelsHub** [comment]
need add arg3 - whether the timer was successfully set.

**Comment by NovaRain** [comment]
Is it normal that the value of ret2 only effects the displayed message? With test script:
```
procedure start;

#include ".\HEADERS\DEFINE.H"
#include ".\headers\sfall.h"

procedure start begin
   if game_loaded then begin
      register_hook(33);
   end else begin
      variable
         timerTicks := get_sfall_arg,
         explosive := get_sfall_arg;

      display_msg("Set " + obj_name(explosive) + " timer: " + timerTicks + " ticks.");
      set_sfall_return(timerTicks);
      set_sfall_return(1); // always fail
   end
end
```
The explosive detonates on time from a character with Trap 150%. Only the message says it "detonates prematurely" (failure message).

BTW, I'd rename it to HOOK_EXPLOSI**VE**TIMER, since dynamites and Cordex are *explosive*s not explosion.

**Comment by FakelsHub** [comment]
> Is it normal that the value of ret2 only effects the displayed message?

I did not study the engine queue system, it's possible that something else is affecting it.

> ExplosiveTimer

ok

**Comment by NovaRain** [comment]
Tested with another character with poor Trap skill, and the explosive still detonates on time but with failure message. The explosive does detonate prematurely without the script. For now ret2 doesn't really make the explosive detonate prematurely but is only for displaying the failure message.

**Comment by FakelsHub** [comment]
Hook completely override the set of the timer, so here everything is in the hands of the moder to control the process.

**Comment by FakelsHub** [comment]
Updated the implementation of the hook.

**Pull request merged**
