### PR TITLE
Autobuild binaries

### PR DESCRIPTION
**Pull request by wipe2238**
Adds GitHub Actions building ddraw.dll from scratch, and a simple workflow using it.

---

Unlike most of autobuild actions around, this one is using `action.yml`; that allows external repositories (mods) to re-use it without much effort or knowledge about building Windows libraries process. As all steps required for successful build remains in sfall repository, it can be tweaked/modified anytime without need to inform modders about all little details.

(NOTE: on its own, `action.yml` is completely passive, and cannot do anything - it must be actually used by some workflow first)

#### Example usage
```yaml
- name: Build sfall
  id:   sfall
  uses: phobos2077/sfall@develop
  with:
   release-xp: true

- name: Copy sfall to mod directory
  run:  |
         copy "${{ steps.sfall.outputs.release-xp }}" "my/mod/directory/ddraw.dll"
```
Builds WIP ddraw.dll using `ReleaseXP` configuration and copies it to selected directory.

```yaml
- name: Build sfall
  id:   sfall
  uses: phobos2077/sfall@master
  with:
   release-xp: true
  dev-xp: true

- name: Copy sfall to mod directory
  run:  |
        copy "${{ steps.sfall.outputs.release-xp }}" "my/mod/directory/ddraw.dll"
        copy "${{ steps.sfall.outputs.dev-xp }}" "my/mod/directory/dev/ddraw.dll"
        copy "${{ steps.sfall.outputs.dev-pdb }}" "my/mod/directory/dev/ddraw.pdb"
```
Builds latest official release using `ReleaseXP` and `DevXP` configurations and copies results to selected directories.
(This will start to work after `action.yml` is merged into default branch)

---

Attached workflow (`build.yml`) uses action mentioned above, (re)compiles ddraw.dll [on each commit] using `ReleaseXP` and `DevXP` configurations, and uploads it to GitHub as an artifact. That allows modders which doesn't use GitHub Actions to test pre-release sfall versions without much trouble. I've changed artifact lifetime from default 90 to 14 days, which should be enough for an average modder actively testing new WIP sfall.

NOTE: both (re)compilation and artifact uploading is currently enabled only for pushes to `develop`/`github-action` branches, and ignores commits which doesn't change anything in sfall code or related .yml files.

### CODE REVIEW

**Comment by FakelsHub** [comment]
Then the network will walk all sorts of unfinished release versions?
if you do it only for dev builds.

**Comment by wipe2238** [comment]
Artifacts are uploded only for `develop` commits, and are kept for only for 2 weeks; after that they're gone from GitHub.
Long enough to test new things, not long enough to risk that modders will start using old WIP versions.

**Comment by FakelsHub** [comment]
develop == unfinished ReleaseXP

**Comment by wipe2238** [comment]
I'm sorry, but i have no idea what you're trying to say here.

**Comment by FakelsHub** [comment]
What I'm saying is that the release build should be banned to avoid unnecessary complaints from users, and build only the dev version.
The fact that this is stored for 14 days does not matter, will you delete all incomplete releases from other users?.

**Comment by NovaRain** [comment]
> avoid unnecessary complaints from users

I think it wouldn't hurt to ask the issue opener what's the date of the binary he's using.

**Comment by FakelsHub** [comment]
usually for this used additionally the 'build' numbering.

**Pull request merged**
