### PR TITLE
 Refactoring hooks.

### PR DESCRIPTION
**Pull request by FakelsHub**
Added auxiliary argument arg5 (always value -1) for hook HOOK_DEATHANIM1, for compatibility with hook HOOK_DEATHANIM2, when using common script procedure.

### CODE REVIEW

**Comment by phobos2077** [comment]
Was this tested?

**Comment by FakelsHub** [comment]
Что именно? Изменения в HOOK_DEATHANIM1/HOOK_DEATHANIM2 - я протестировал. В остальном там ничего не менялось.

**Comment by FakelsHub** [comment]
Please make merge.

**Comment by FakelsHub** [comment]
I have this script working.

**Comment by FakelsHub** [comment]
I made a merge into the develop branch, checked this script - it works.

**Comment by NovaRain** [comment]
The script only works when I enable InjectAllGameHooks in [Debugging], and it's definitely wrong.

**Comment by FakelsHub** [comment]
ok)

**Pull request merged**
