### PR TITLE
Adding hook HOOK_DESCRIPTIONOBJ and functions dialog_message/get_string_pointer

### PR DESCRIPTION
**Pull request by FakelsHub**
To the BarterPrice hook, the second returned argument is added, to change the price of the offered goods.

### CODE REVIEW

**Comment by NovaRain** [comment]
Just did a quick test for the 'fix' of displaying full weapon/ammo description in the barter screen. There's a glitch that the item description of many weapons gets cut:
Imgur

IMO it's better not to display their description at all, unless it can be fully displayed without cut-off.

**Comment by FakelsHub** [comment]
> The item description of many weapons will get cut off

It seems that I too much cut the buffer `strncpy_s (textBuf, desc, 128)` initially it was 512.
OK, I'll analyze again the maximum size for the description.

> Also I'd give it an option in the INI, since it doesn't really fix anything that's "broken" in vanilla game.

This is a vanilla error and should be fixed without any Ini
This fix is necessary for the work of the Hook itself

**Comment by NovaRain** [comment]
>Also fix is necessary for the work of the Hook itself.

I was wondering about what the usage scenario of the new hook and functions (plus the new game mode), do they have anything to do with the game hints you guys discussed in Sonora thread? Care to provide an example?

BTW, you should separate independent features in different PR instead of a "bundle" PR. The extended hook_barterprice doesn't have any dependency with hook_descriptionobj.

**Comment by FakelsHub** [comment]
Also fix is necessary for the work of the **HOOK_DESCRIPTIONOBJ** itself.

> Care to provide an example?

_Allows to override the description of the item (for example: add additional custom parameters to the description)._
Simple example:
```
HOOK_DESCRIPTIONOBJ
   pid = obj_pid(get_sfall_arg);
   id = get_proto_data(pid, PROTO_TEXTID);
   itemdesc = message_str_game(GAME_MSG_PRO_ITEM, id)
   itemdesc += "Your text";
   set_sfall_return(get_message_pointer(itemdesc);
```

**Comment by FakelsHub** [comment]
> BTW, you should separate independent features into different PRs instead of a "bundle" PR.

What is this separate for? it's too long for me, I have 1 month of time ahead, I still have 4-5 features for adding, and then I switch completely to my project and I will not go back to sfall (until some new need arises).

**Comment by NovaRain** [comment]
>What is this separate for? it's too long for me, I have 1 month of time ahead, I still have 4-5 features for adding, and then I switch completely to my project and I will not go back to sfall (until some new need arises).

It would be easier for me to test and manage your PRs. You have your time frame, I have mine. Especially I will be kinda busy in August due to the incoming heavy workload in my job.

**Pull request merged**
