### PR TITLE
Hero appearance background image.

### PR DESCRIPTION
**Pull request by FakelsHub**
If the catalogue `art/intrface` to placed the files `AppChCrt.frm` and `AppChEdt.frm` then they will be used as an interface image for the appearance mod.

ps: Can I make a pull for version 4.0, or will you do it yourself?

### CODE REVIEW

**Comment by NovaRain** [comment]
If you want to replace the background image of character editor/screen, why not just replacing vanilla EDTRCRTE/EDTREDT.frm?

**Comment by NovaRain** [comment]
It's recommended to use the develop branch for pull requests, especially when it comes to adding new features. Also I'm planning to stop releasing 3.8.x "ESR" soon because 4.0.x is proven to be stable enough.

**Comment by FakelsHub** [comment]
Here you could use this code, and then remove the unnecessary insertion of asm code.
`UNLSTDfrm *frm = LoadUnlistedFrm((_glblmode) ? "AppChCrt.frm" : "AppChEdt.frm", 6);`

**Comment by FakelsHub** [comment]
> It's recommended to use the develop branch for pull requests, especially when it comes to adding new features.

Ok. 
The more I look at the sfall code, I understand that it needs to be reworked, starting from the incorrect implementation of hooks system. + it is necessary to refactoring the code.

**Comment by NovaRain** [comment]
It seems the simplified code will cause AppChCrt.frm overwriting AppChEdt.frm. Guess I rushed the commit in 4.0.

**Comment by FakelsHub** [comment]
Need use `*(DWORD**)_glblmode`

**Pull request merged**
