### PR TITLE
Improvement HOOK_INVENTORYMOVE & HOOK_INVENWIELD.

### PR DESCRIPTION
**Pull request by FakelsHub**
New event for arg1 to HOOK_INVENTORYMOVE
5 - Moving item to the container. (and arg3 - returns a pointer to the container).
6 - Dropping of item to ground through the menu icon.

HOOK_INVENWIELD
Added possible to get a pointer an item object before unweld it.

### CODE REVIEW

**Comment by NovaRain** [comment]
>HOOK_INVENWIELD
Added possible to get a pointer an item object before unweld it.

I thought HOOK_INVENWIELD already runs before wielding or unwielding. What's the difference between your changes and the current implementation? Will it affect existing scripts in any way?

**Comment by FakelsHub** [comment]
```
obj  arg2 - item being wielded or unwielded (weapon/armor), may be 0 when unwielding
```
invenUnwieldFunc_Hook, always returned 0, now returns a pointer to the item.

**Comment by FakelsHub** [comment]
> I thought HOOK_INVENWIELD already runs before wielding or unwielding.

Returned only if the item was removed(unwield) by the functions op_move_obj_inven_to_obj_ and op_rm_obj_from_inven_

**Comment by FakelsHub** [comment]
> That's a tough one...
???

**Comment by NovaRain** [comment]
Just noticed a minor bug in both 3.8 and 4.0 (even with your code), when using a hs_inventorymove.int test script like this:
```
procedure start begin
   if not init_hook then begin
      variable
         slot := get_sfall_arg,
         itemMoved := get_sfall_arg,
         itemReplaced := get_sfall_arg;

      // old
      if (slot <= 4) then begin
         display_msg("Moved " + obj_name(itemMoved) + " to Slot:" + slot);
         if itemReplaced then display_msg("Replaced: " + obj_name(itemReplaced));
      end

      // new
      if (slot == 5) then begin
         display_msg("Moved " + obj_name(itemMoved) + " to Container:" + obj_name(itemReplaced));
      end
      if (slot == 6) then begin
         display_msg("Dropped " + obj_name(itemMoved) + " to the ground.");
      end

      //set_sfall_return(-1);
   end
end
```
Reloading weapons in the inventory by dropping ammo on them does not play their reloading sound. Looks like DropAmmoIntoWeaponHack() might need some tweaking.

Also, it seems moving items to a container doesn't work, as the test script prints nothing. But dropping items on the ground works.

**Comment by FakelsHub** [comment]
> Reloading weapons in the inventory by dropping ammo on them does not play their reloading sound. 

I have a sound!

> Also, it seems moving items to a container doesn't work, as the test script prints nothing. 

I have your test script working completely.
I found a small bug when the container is in the slot of the hand and the object is moved to it.

**Comment by NovaRain** [comment]
>I have a sound!
Maybe you meant that it should not be if the store is fully charged?

No. The reloading sound I got with the test script is completely different from without it.

**Comment by FakelsHub** [comment]
OK. I will check.

**Comment by FakelsHub** [comment]
I checked the reloading sounds... I have different reloading sounds.
What is wrong there?

**Comment by FakelsHub** [comment]
> when dropping ammo to weapons in the inventory

 Checked it. no problem.
_apparently you have a problem in win10))))_

**Comment by NovaRain** [comment]
>I Checked it. no problem.
apparently you have a problem in win10))))
try to find the problem yourself and fix it.

I'm using Win7, and I've been testing in two different PCs and got the same issue. Fine, since other things have been checked out, I'll merge this anyway.

**Comment by FakelsHub** [comment]
> I found the cause of my "no reloading sound" issue: setting IFACE_BAR_WIDTH=800 in HRP. Changing it back to default 640 and the issue is gone.

I do not have problems with recharging sound with both mode(800 and 640) :)
I can't understand how Hook can affect sound.

**Comment by NovaRain** [comment]
>I do not have problems with reloading sound with both mode(800 and 640) :)
I can't understand how Hook can affect sound.

Neither do I, but at least changing the option works for both of my PCs so it's fine.

**Comment by FakelsHub** [comment]
Have you tried to test this problem on the version of Crafty?

**Comment by NovaRain** [comment]
>Have you tried to test this problem on the version of Crafty?

Just did, and it's the same. I'd guess for some reason the notice sound for new messages takes priority over the reloading sound, but I don't plan to dig this issue any further.

**Comment by FakelsHub** [comment]
In the version of the @Crafty, the behavior of recharging is corrected, when the magazine is fully charged, recharging does not occur, as when trying to charge with other types of ammo.
I think it is also worth fixing?

**Pull request merged**
