### PR TITLE
Fix bug playing animation when critter goes through the door.

### PR DESCRIPTION
**Pull request by FakelsHub**
Are there any questions?)

### CODE REVIEW

**Comment by NovaRain** [comment]
>Are there any questions?)

Yes. A demo video of the game crash would be nice, because it seems the game doesn't crash from [your video in the post on Fallout.ru](http://fforum.kochegarov.com/index.php?showtopic=29288&view=findpost&p=343635). Or is it just bugged (your title) but not crashed (comment in line 320)?

**Comment by FakelsHub** [comment]
> because it seems the game doesn't crash from your video in the post on Fallout.ru.

This bug is also in the original, but with the AnimationsAtOnceLimit option disabled.
In addition, the code suppresses the possibility for a player to pass through a door that does not open with the ThruWalk flag set.

> Also does it only happen when using the auto door script?

No, at any door, if through such a door there is a critter.

**Comment by NovaRain** [comment]
I was trying to reproduce the crash in my game. I added a door frame and a door (with doorl100.int) in artemple.map, and placed a spatial script, which is modified cimine.int to deal 10000 explosion damage to the player but without explosion effect, at the door hex. But when I unlock the door and run through it, I only get blown to pieces at the door hex without any shift or crash. Did I set up things wrong?

**Comment by FakelsHub** [comment]
[door test](https://youtu.be/1GNFp9lPsWA)
This is a normal door without the flag ThruWalk, in the use_p_proc handler used reg_anim_func (2, source_obj)
Perhaps this bug happens under certain conditions, and apparently you do not have it, and I have not seen such a mistake before.

Maybe then you'll make a fix via an ini option?

**Comment by FakelsHub** [comment]
I checked [this](https://youtu.be/X8Eh_-UL7Mc) also on the original F2 on sfall 3.8.9 (AnimationsAtOnceLimit = 0) and I get the same crash of the game.

**Comment by NovaRain** [comment]
>[door test](https://youtu.be/1GNFp9lPsWA)
This is a normal door without the flag ThruWalk, in  script door  the use_p_proc handler used critter_dmg(source_obj, 10, 0) or reg_anim_func (2, source_obj)

Great, thanks for the video. I got the same crash by provoking other critter (poor Klint) and letting him go through the scripted door, with AnimationsAtOnceLimit disabled.

**Pull request merged**
