### PR TITLE
Fixed functions op_obj_can_see_obj_/op_obj_can_hear

### PR DESCRIPTION
**Pull request by FakelsHub**

### CODE REVIEW

**Comment by NovaRain** [comment]
I know that obj_can_hear_obj is broken, but what is the bug from obj_can_see_obj?

**Comment by FakelsHub** [comment]
An additional check for the elevation, if the objects are on different floors then the function is_within_perception_ will not be called.
is_within_perception_ does not check floors, so it will return 'True'
Just programmers were under alcohol and wrote shit-code.

**Comment by NovaRain** [comment]
obj_can_see_obj itself doesn't seem to have any problem when source and target are on different elevations. I added a line to print message if Cassidy can see PC in his critter_p_proc. The message doesn't pop out when I'm on a different elevation (tested with NEWR3.map).

**Comment by FakelsHub** [comment]
**is_within_perception_ does not check elevation, so it will return 'True' in HOOK_WITHINPERCEPTION**

**Comment by FakelsHub** [comment]
> so the fix was mainly for when working with the hook, not the function itself.

And an absent check for the source was added if ( source->tile_num != -1 )

**Comment by FakelsHub** [comment]
The code of the engine after the fix has become this.
```
 if ( target && source ) {
   v13 = target->elev;
   v14 = source->elev;
   if ( v13 == v14 ) {
      if (source->tile_num != -1 && target->tile_num != -1 )  {
         if ( is_within_perception_(source, target) ) {
            make_straight_path_(source, target->tile_num, 0, *(source + offsetof(pobj, tile_num)), &buf, 16);
            if ( target == buf )  {
               v20 = 1;
            }
         }
      }
   }
}
```

**Pull request merged**
